services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: elekto
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
