include:
  - ../docker-compose.yml # Defines the `db` service
  - ./services/github-static-mock/docker-compose.yaml # Defines the `github` mock backend service

services:
  integration_tests:
    build: .
    environment:
      ELEKTO_HOST: "elekto:8000"
      GITHUB_HOST: "github:9000"
    depends_on:
      elekto:
        condition: service_healthy
      db:
        condition: service_healthy
    profiles:
      - test
    volumes:
      - "./tests:/app/tests"
  elekto:
    build: ../
    user: "root" # To access /app/meta/.git/FETCH_HEAD
    ports:
      # Links will point to `http://elekto:8000/`, so you must manually patch the URLs to localhost in your browser
      # after each redirect. Exposing the Elekto service allows for manual checking during tests if desired.
      - "8000:8000"
    environment:
      DONT_OVERRIDE_ENV_VARS: true  # prioritize all settings that were already set in env before loading .env file
      DB_CONNECTION: postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: root
      DB_DATABASE: elekto
      INTEGRATION_TEST: true
      APP_PORT: 8000
      META_REPO: https://github.com/elekto-dev/elekto.meta.test.git
      ELECTION_DIR: elections
      META_DEPLOYMENT: local
      META_PATH: meta
      META_BRANCH: main
      META_SECRET: xxx
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8000/app/" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - test
